services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/fulebuddy
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 