Table User {
  _id ObjectId [pk]
  email String [unique, not null]
  name String [not null]
  password String [not null, note: 'Hashed password']
}

Table Task {
  _id ObjectId [pk]
  title String [not null]
  description String [not null]
  createdBy ObjectId [ref: > User._id]
  sharedWith ObjectId [ref: > User._id]
} 